version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres.dntbjamxbaoguowcynfa:kY2Y9QjFYt1MbHE7@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?prepared_statements=false&pgbouncer=true&connection_limit=1
      - DIRECT_URL=postgresql://postgres:kY2Y9QjFYt1MbHE7@db.dntbjamxbaoguowcynfa.supabase.co:5432/postgres
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=pet-management-secret-key-development-2024
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    networks:
      - pet-network
    restart: unless-stopped

  
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres.dntbjamxbaoguowcynfa:kY2Y9QjFYt1MbHE7@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?prepared_statements=false&pgbouncer=true&connection_limit=1
    networks:
      - pet-network
    profiles:
      - tools

volumes:
  postgres_data:

networks:
  pet-network:
    driver: bridge